### ISSUE TITLE
`TODO: -- remove these once Yazi 0.4 gets released`

### ISSUE THREAD

**Issue by azzamsa** [yazi-rs/flavors#33]
Hi. 👋🏽 

Yazi https://github.com/sxyazi/yazi/releases/tag/v0.4.0 is released 🎉 

Should I make appropriate PR?

Thanks for Yazi.

**Comment by sxyazi** [comment]
Should be fixed in https://github.com/yazi-rs/flavors/commit/fc8eeaab9da882d0e77ecb4e603b67903a94ee6e, thanks for the reminder!
